In [21]:
import numpy as np
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [22]:
array = np.linspace(-3,3,num=100)
array * 10

array([-30.        , -29.39393939, -28.78787879, -28.18181818,
       -27.57575758, -26.96969697, -26.36363636, -25.75757576,
       -25.15151515, -24.54545455, -23.93939394, -23.33333333,
       -22.72727273, -22.12121212, -21.51515152, -20.90909091,
       -20.3030303 , -19.6969697 , -19.09090909, -18.48484848,
       -17.87878788, -17.27272727, -16.66666667, -16.06060606,
       -15.45454545, -14.84848485, -14.24242424, -13.63636364,
       -13.03030303, -12.42424242, -11.81818182, -11.21212121,
       -10.60606061, -10.        ,  -9.39393939,  -8.78787879,
        -8.18181818,  -7.57575758,  -6.96969697,  -6.36363636,
        -5.75757576,  -5.15151515,  -4.54545455,  -3.93939394,
        -3.33333333,  -2.72727273,  -2.12121212,  -1.51515152,
        -0.90909091,  -0.3030303 ,   0.3030303 ,   0.90909091,
         1.51515152,   2.12121212,   2.72727273,   3.33333333,
         3.93939394,   4.54545455,   5.15151515,   5.75757576,
         6.36363636,   6.96969697,   7.57575758,   8.18181818,
         8.78787879,   9.39393939,  10.        ,  10.60606061,
        11.21212121,  11.81818182,  12.42424242,  13.03030303,
        13.63636364,  14.24242424,  14.84848485,  15.45454545,
        16.06060606,  16.66666667,  17.27272727,  17.87878788,
        18.48484848,  19.09090909,  19.6969697 ,  20.3030303 ,
        20.90909091,  21.51515152,  22.12121212,  22.72727273,
        23.33333333,  23.93939394,  24.54545455,  25.15151515,
        25.75757576,  26.36363636,  26.96969697,  27.57575758,
        28.18181818,  28.78787879,  29.39393939,  30.        ])

In [23]:
np.random.randint(50,size=100,high=101)

array([ 60,  50,  72,  75,  67,  71,  78,  55,  98,  72,  79, 100,  65,
        91,  91,  79,  87,  87,  74,  72,  97,  70,  61,  68,  58,  73,
        77,  79,  51,  75,  77,  57,  62,  66,  91,  69,  86,  79,  93,
        83,  89,  68,  57,  87,  98,  54,  81,  61,  75,  82,  66,  69,
        87,  54,  90,  67,  96,  52,  69,  85,  72,  69,  91,  53,  65,
        98,  63,  93,  72,  77,  74,  68,  63,  54,  51,  74,  69,  95,
        87,  87,  63,  99,  81,  56,  72,  68,  89,  90,  97,  68,  84,
        79,  76,  84,  70,  61,  93,  84,  80,  59])

In [24]:
content = np.random.randint(50,size=(50,5),high=101)

In [25]:
import pandas as pd
df1 = pd.DataFrame(data=content,
             index=range(1,51),
             columns=['國文','英文','數學','地理','歷史'])
df1

     國文  英文   數學  地理   歷史
1    74  54   70  74  100
2    57  90   89  67   68
3    68  87   66  54   91
4    58  85  100  89   63
5    98  90   93  85   62
6    97  67   97  93   59
7    59  72   82  93   75
8    74  84   95  70   88
9    61  98   71  52   97
10   87  96   71  85   64
11   94  61   53  86   70
12   74  75   57  84   77
13   73  96   81  91   76
14   93  82   86  75   88
15   52  88   96  84   60
16   99  63   89  71   63
17   64  61  100  56   81
18   98  73   54  77   85
19   77  78   56  99   57
20   81  70   96  72   98
21   85  87   61  74   85
22   90  64   94  74   95
23   79  99   74  68   65
24   54  55   76  67   70
25   59  63   68  98   87
26   84  66   74  76   94
27   72  57   69  67   93
28   87  83   66  73   62
29   65  74   79  68   88
30   78  85   57  50   82
31   76  58   82  98   58
32   72  67   79  51   63
33   83  52   81  65   50
34   55  69   87  73   68
35   83  96   95  89   70
36   54  52   60  80   53
37   54  66   58  50   62
38   88  94   62  69   92
39   82  62   73  50   91
40   72  64   57  61   82
41   55  56   58  89   86
42   67  92   67  64   82
43   92  96   64  83   53
44   82  50   81  88   65
45   94  90   53  97   79
46   68  80   50  87   73
47   61  58   75  85   54
48   97  60   80  57   82
49  100  71   57  71   83
50   64  83   65  95   53

In [26]:
df1['國文'] + df1['英文'] + df1['數學'] + df1['地理'] + df1['歷史']

1     372
2     371
3     366
4     395
5     428
6     413
7     381
8     411
9     379
10    403
11    364
12    367
13    417
14    424
15    380
16    385
17    362
18    387
19    367
20    417
21    392
22    417
23    385
24    322
25    375
26    394
27    358
28    371
29    374
30    352
31    372
32    332
33    331
34    352
35    433
36    299
37    290
38    405
39    358
40    336
41    344
42    372
43    388
44    366
45    413
46    358
47    333
48    376
49    382
50    360
dtype: int64

In [27]:
import pandas as pd
df1 = pd.DataFrame(data=content,
             index=[f"第{i}號"for i in range(1,51)],
             columns=['國文','英文','數學','地理','歷史'])
df1

       國文  英文   數學  地理   歷史
第1號    74  54   70  74  100
第2號    57  90   89  67   68
第3號    68  87   66  54   91
第4號    58  85  100  89   63
第5號    98  90   93  85   62
第6號    97  67   97  93   59
第7號    59  72   82  93   75
第8號    74  84   95  70   88
第9號    61  98   71  52   97
第10號   87  96   71  85   64
第11號   94  61   53  86   70
第12號   74  75   57  84   77
第13號   73  96   81  91   76
第14號   93  82   86  75   88
第15號   52  88   96  84   60
第16號   99  63   89  71   63
第17號   64  61  100  56   81
第18號   98  73   54  77   85
第19號   77  78   56  99   57
第20號   81  70   96  72   98
第21號   85  87   61  74   85
第22號   90  64   94  74   95
第23號   79  99   74  68   65
第24號   54  55   76  67   70
第25號   59  63   68  98   87
第26號   84  66   74  76   94
第27號   72  57   69  67   93
第28號   87  83   66  73   62
第29號   65  74   79  68   88
第30號   78  85   57  50   82
第31號   76  58   82  98   58
第32號   72  67   79  51   63
第33號   83  52   81  65   50
第34號   55  69   87  73   68
第35號   83  96   95  89   70
第36號   54  52   60  80   53
第37號   54  66   58  50   62
第38號   88  94   62  69   92
第39號   82  62   73  50   91
第40號   72  64   57  61   82
第41號   55  56   58  89   86
第42號   67  92   67  64   82
第43號   92  96   64  83   53
第44號   82  50   81  88   65
第45號   94  90   53  97   79
第46號   68  80   50  87   73
第47號   61  58   75  85   54
第48號   97  60   80  57   82
第49號  100  71   57  71   83
第50號   64  83   65  95   53

In [28]:
df1.loc[["第1號","第5號","第10號"]]

      國文  英文  數學  地理   歷史
第1號   74  54  70  74  100
第5號   98  90  93  85   62
第10號  87  96  71  85   64

In [29]:
df1.iloc[:5]

     國文  英文   數學  地理   歷史
第1號  74  54   70  74  100
第2號  57  90   89  67   68
第3號  68  87   66  54   91
第4號  58  85  100  89   63
第5號  98  90   93  85   62

In [30]:
df1.iloc[-5:]

       國文  英文  數學  地理  歷史
第46號   68  80  50  87  73
第47號   61  58  75  85  54
第48號   97  60  80  57  82
第49號  100  71  57  71  83
第50號   64  83  65  95  53

In [31]:
df1.loc['第10號':'第15號']

      國文  英文  數學  地理  歷史
第10號  87  96  71  85  64
第11號  94  61  53  86  70
第12號  74  75  57  84  77
第13號  73  96  81  91  76
第14號  93  82  86  75  88
第15號  52  88  96  84  60

In [32]:
df1.loc['第10號':'第15號','國文']

第10號    87
第11號    94
第12號    74
第13號    73
第14號    93
第15號    52
Name: 國文, dtype: int64

In [33]:
df1.loc['第10號':'第15號',['國文','數學']]

      國文  數學
第10號  87  71
第11號  94  53
第12號  74  57
第13號  73  81
第14號  93  86
第15號  52  96

In [34]:
df1.loc[['第10號','第15號'],['國文','數學']]

      國文  數學
第10號  87  71
第15號  52  96

In [35]:
student_sum = df1.sum(axis=1)
student_mean = df1.mean(axis=1)
df1['總分'] = student_sum
df1['平均'] = student_mean
df1

       國文  英文   數學  地理   歷史   總分    平均
第1號    74  54   70  74  100  372  74.4
第2號    57  90   89  67   68  371  74.2
第3號    68  87   66  54   91  366  73.2
第4號    58  85  100  89   63  395  79.0
第5號    98  90   93  85   62  428  85.6
第6號    97  67   97  93   59  413  82.6
第7號    59  72   82  93   75  381  76.2
第8號    74  84   95  70   88  411  82.2
第9號    61  98   71  52   97  379  75.8
第10號   87  96   71  85   64  403  80.6
第11號   94  61   53  86   70  364  72.8
第12號   74  75   57  84   77  367  73.4
第13號   73  96   81  91   76  417  83.4
第14號   93  82   86  75   88  424  84.8
第15號   52  88   96  84   60  380  76.0
第16號   99  63   89  71   63  385  77.0
第17號   64  61  100  56   81  362  72.4
第18號   98  73   54  77   85  387  77.4
第19號   77  78   56  99   57  367  73.4
第20號   81  70   96  72   98  417  83.4
第21號   85  87   61  74   85  392  78.4
第22號   90  64   94  74   95  417  83.4
第23號   79  99   74  68   65  385  77.0
第24號   54  55   76  67   70  322  64.4
第25號   59  63   68  98   87  375  75.0
第26號   84  66   74  76   94  394  78.8
第27號   72  57   69  67   93  358  71.6
第28號   87  83   66  73   62  371  74.2
第29號   65  74   79  68   88  374  74.8
第30號   78  85   57  50   82  352  70.4
第31號   76  58   82  98   58  372  74.4
第32號   72  67   79  51   63  332  66.4
第33號   83  52   81  65   50  331  66.2
第34號   55  69   87  73   68  352  70.4
第35號   83  96   95  89   70  433  86.6
第36號   54  52   60  80   53  299  59.8
第37號   54  66   58  50   62  290  58.0
第38號   88  94   62  69   92  405  81.0
第39號   82  62   73  50   91  358  71.6
第40號   72  64   57  61   82  336  67.2
第41號   55  56   58  89   86  344  68.8
第42號   67  92   67  64   82  372  74.4
第43號   92  96   64  83   53  388  77.6
第44號   82  50   81  88   65  366  73.2
第45號   94  90   53  97   79  413  82.6
第46號   68  80   50  87   73  358  71.6
第47號   61  58   75  85   54  333  66.6
第48號   97  60   80  57   82  376  75.2
第49號  100  71   57  71   83  382  76.4
第50號   64  83   65  95   53  360  72.0

In [36]:
df2 = df1.sort_values(by='總分',ascending=False)

In [37]:
df2.iloc[:5]

      國文  英文  數學  地理  歷史   總分    平均
第35號  83  96  95  89  70  433  86.6
第5號   98  90  93  85  62  428  85.6
第14號  93  82  86  75  88  424  84.8
第13號  73  96  81  91  76  417  83.4
第20號  81  70  96  72  98  417  83.4

In [38]:
df2.iloc[-5:]

      國文  英文  數學  地理  歷史   總分    平均
第32號  72  67  79  51  63  332  66.4
第33號  83  52  81  65  50  331  66.2
第24號  54  55  76  67  70  322  64.4
第36號  54  52  60  80  53  299  59.8
第37號  54  66  58  50  62  290  58.0

In [39]:
df2['排名'] = df1['總分'].rank(method='first',ascending=False)
df2

       國文  英文   數學  地理   歷史   總分    平均    排名
第35號   83  96   95  89   70  433  86.6   1.0
第5號    98  90   93  85   62  428  85.6   2.0
第14號   93  82   86  75   88  424  84.8   3.0
第13號   73  96   81  91   76  417  83.4   4.0
第20號   81  70   96  72   98  417  83.4   5.0
第22號   90  64   94  74   95  417  83.4   6.0
第45號   94  90   53  97   79  413  82.6   8.0
第6號    97  67   97  93   59  413  82.6   7.0
第8號    74  84   95  70   88  411  82.2   9.0
第38號   88  94   62  69   92  405  81.0  10.0
第10號   87  96   71  85   64  403  80.6  11.0
第4號    58  85  100  89   63  395  79.0  12.0
第26號   84  66   74  76   94  394  78.8  13.0
第21號   85  87   61  74   85  392  78.4  14.0
第43號   92  96   64  83   53  388  77.6  15.0
第18號   98  73   54  77   85  387  77.4  16.0
第16號   99  63   89  71   63  385  77.0  17.0
第23號   79  99   74  68   65  385  77.0  18.0
第49號  100  71   57  71   83  382  76.4  19.0
第7號    59  72   82  93   75  381  76.2  20.0
第15號   52  88   96  84   60  380  76.0  21.0
第9號    61  98   71  52   97  379  75.8  22.0
第48號   97  60   80  57   82  376  75.2  23.0
第25號   59  63   68  98   87  375  75.0  24.0
第29號   65  74   79  68   88  374  74.8  25.0
第1號    74  54   70  74  100  372  74.4  26.0
第31號   76  58   82  98   58  372  74.4  27.0
第42號   67  92   67  64   82  372  74.4  28.0
第2號    57  90   89  67   68  371  74.2  29.0
第28號   87  83   66  73   62  371  74.2  30.0
第19號   77  78   56  99   57  367  73.4  32.0
第12號   74  75   57  84   77  367  73.4  31.0
第3號    68  87   66  54   91  366  73.2  33.0
第44號   82  50   81  88   65  366  73.2  34.0
第11號   94  61   53  86   70  364  72.8  35.0
第17號   64  61  100  56   81  362  72.4  36.0
第50號   64  83   65  95   53  360  72.0  37.0
第39號   82  62   73  50   91  358  71.6  39.0
第46號   68  80   50  87   73  358  71.6  40.0
第27號   72  57   69  67   93  358  71.6  38.0
第30號   78  85   57  50   82  352  70.4  41.0
第34號   55  69   87  73   68  352  70.4  42.0
第41號   55  56   58  89   86  344  68.8  43.0
第40號   72  64   57  61   82  336  67.2  44.0
第47號   61  58   75  85   54  333  66.6  45.0
第32號   72  67   79  51   63  332  66.4  46.0
第33號   83  52   81  65   50  331  66.2  47.0
第24號   54  55   76  67   70  322  64.4  48.0
第36號   54  52   60  80   53  299  59.8  49.0
第37號   54  66   58  50   62  290  58.0  50.0